# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-06 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('footer_about', models.TextField(blank=True)),
                ('footer_links', models.TextField(blank=True)),
                ('footer_social', models.TextField(blank=True)),
                ('copyright', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'layout',
            },
        ),
    ]
