# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-07 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, help_text='Optional name', max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('notes', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
