# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-06 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('left_column', models.TextField(blank=True)),
                ('right_column', models.TextField(blank=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'sections',
            },
        ),
        migrations.CreateModel(
            name='ServicePod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=255)),
                ('sort_order', models.IntegerField(default=0, help_text='use positions 1 to 6')),
                ('delay', models.IntegerField(default=0, help_text='Milliseconds delay each items display on screen')),
            ],
            options={
                'db_table': 'service_pods',
            },
        ),
    ]
