# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-31 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180115_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='registered_online',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterModelTable(
            name='participant',
            table='participant',
        ),
    ]
