# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-31 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20180131_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='slug',
            field=models.CharField(default='abc', max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
