# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-31 19:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_page_slug'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='page',
            table='page',
        ),
    ]
